micronaut:
  server:
    port: 8080
  security:
    enabled: false

kestra:
  repository:
    type: postgres
  queue:
    type: postgres
  storage:
    type: local
    local:
      base-path: /app/kestra/data
  jdbc:
    url: jdbc:postgresql://postgres-stock:5432/kestra_stock
    username: kestra_stock
    password: stock_market_2024
    driverClassName: org.postgresql.Driver
  server:
    access-log:
      enabled: true
  tasks:
    scripts:
      docker:
        default-options:
          network-mode: host
          auto-remove: true
          memory: 512m
          memory-swap: 512m
          cpus: 1.0
          env:
            GOOGLE_APPLICATION_CREDENTIALS: /app/kestra/service-account-key.json
  plugins:
    repositories:
      central:
        url: https://repo.maven.apache.org/maven2/
    includes:
      - io.kestra.plugin:plugin-core
      - io.kestra.plugin:plugin-scripts
      - io.kestra.plugin:plugin-git
      - io.kestra.plugin:plugin-dbt
      - io.kestra.plugin:plugin-notifications
      - io.kestra.plugin:plugin-gcp
      - io.kestra.plugin:plugin-serdes
